# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: af1fa4aee984b94c72bc4d334e34269229ae497473c2be01b91aeea042d1fb3f49756d5b2e293ce9986f3362318dcb98cb85b8bf13b3077fe6a74bdbb35ccc0c

test:
  secret_key_base: f091b66f96e75cdca78a895bb18a31843012b65e65cc5fb0a4de5f06ecbc00f6ded62528b0923ccfede65e7dff7a55c900b3e819ca992ed7725d7cf2ef27d0c9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
